// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9NpAwFvKy3Vnp9sPTfLG9iuDrsbowXtI',
    appId: '1:50778628971:web:f7b789155622feabc8a22e',
    messagingSenderId: '50778628971',
    projectId: 'my-cool-project-1202202',
    authDomain: 'my-cool-project-1202202.firebaseapp.com',
    storageBucket: 'my-cool-project-1202202.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD3PqRgTrtcC-iYAWonMfakFNRvP6NHZU',
    appId: '1:50778628971:android:1975e0d13c7828acc8a22e',
    messagingSenderId: '50778628971',
    projectId: 'my-cool-project-1202202',
    storageBucket: 'my-cool-project-1202202.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDML1RmFCgtz4n3Rk5VGVN1z7S_Jl14FBU',
    appId: '1:50778628971:ios:ba2d2c6d197c174fc8a22e',
    messagingSenderId: '50778628971',
    projectId: 'my-cool-project-1202202',
    storageBucket: 'my-cool-project-1202202.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDML1RmFCgtz4n3Rk5VGVN1z7S_Jl14FBU',
    appId: '1:50778628971:ios:ba2d2c6d197c174fc8a22e',
    messagingSenderId: '50778628971',
    projectId: 'my-cool-project-1202202',
    storageBucket: 'my-cool-project-1202202.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9NpAwFvKy3Vnp9sPTfLG9iuDrsbowXtI',
    appId: '1:50778628971:web:ed3e0d0678326c7cc8a22e',
    messagingSenderId: '50778628971',
    projectId: 'my-cool-project-1202202',
    authDomain: 'my-cool-project-1202202.firebaseapp.com',
    storageBucket: 'my-cool-project-1202202.firebasestorage.app',
  );

}